In [1]:
import pandas as pd
fk_rev = pd.read_csv("flip.csv")

In [2]:
fk_rev

Unnamed: 0                  User Name                Heading  Rating  \
0             0           Arunangshu Banik               just wow       5   
1             1             Sachin Pashte                 awesome       5   
2             2        Hari Chandana Petli               terrific       5   
3             3          PRINCE  SEBASTIAN                awesome       5   
4             4              Nagaraju Tech           nice product       4   
5             5           Vijendra Malivad     highly recommended       5   
6             6                Jitu Sonkar            good choice       4   
7             7               Navin Anjani          great product       5   
8             8             Subhajit kundu              excellent       5   
9             9              Sumit  Kumar      highly recommended       5   
10           10          Flipkart Customer         simply awesome       5   
11           11                Sayon Gorai               moderate       4   
12           12               Gourav Singh              wonderful       5   
13           13            Ameya  Banavali  worst experience ever       5   
14           14            Kanishka Mudgal          great product       5   
15           15             Dilruban Ahmad               fabulous       4   
16           16              Modassar Khan      worth every penny       5   
17           17       Dr. Pragnesh  Patni           valueformoney       4   
18           18                AS.  Husain          great product       2   
19           19          Flipkart Customer             delightful       1   
20           20        PREMCHANDRA DIWAKAR      worth every penny       5   
21           21           Sk.Sahina  Siraz         classy product       5   
22           22          Flipkart Customer               just wow       5   
23           23                Badroddin S     best in the market       5   
24           24              Muhmmad Ahmad               fabulous       5   
25           25            Mohammad Shahid              brilliant       5   
26           26          Flipkart Customer          valueformoney       4   
27           27               Diptanu Paul               just wow       5   
28           28              Jayanth Kumar               must buy       5   
29           29               Hariom tejra   good quality product       4   
..          ...                        ...                    ...     ...   
470         470  Thiyagarajan Ramachandran        perfect product       5   
471         471              Korrai Ramesh         simply awesome       5   
472         472                Aditi Anand             delightful       4   
473         473               Mehndi Hasan         simply awesome       5   
474         474         Guru Sundar Ganesh              excellent       5   
475         475                  Asim Gire              wonderful       4   
476         476          Flipkart Customer     highly recommended       5   
477         477          ABHISHEK BHANDARI             delightful       4   
478         478              Pratap Ambade         simply awesome       5   
479         479             Dikshita Sarma                   good       3   
480         480                 Raj Thakur               just wow       5   
481         481               Mark Clement   good quality product       4   
482         482              Jayanthan  CS                awesome       5   
483         483                   Nethra V      worth every penny       5   
484         484              Sumbul Fatema            good choice       4   
485         485                       Abhi   good quality product       4   
486         486               Prashanth  R          valueformoney       4   
487         487          Flipkart Customer         classy product       5   
488         488            JOSEPH SURESH S     highly recommended       5   
489         489             arup kumar das   mindblowing purchase       5   
4

In [3]:
del fk_rev["User Name"]
del fk_rev["Heading"]
del fk_rev["Rating"]
fk_rev

Unnamed: 0                                             Review  \
0             0  i am spellbound after seeing thiswhat a value ...   
1             1  overall the screen of the redmiis pretty good ...   
2             2  awesome mobile ive purchased it for my mom she...   
3             3  very good phonenice display andlong battery li...   
4             4  super budget mobile i like type c portbig exce...   
5             5  it was a very smoothly phone works and also it...   
6             6  nice phone good battery life amazing design ca...   
7             7  redmiin good phone in good processor in goodin...   
8             8  stunning lookgoodpowerful performancepieawesom...   
9             9  wow great phone camera is super and battery is...   
10           10  awesom product from my point of view redmiis t...   
11           11  honest review from a honest buyer i know there...   
12           12  good phone and battery camera goodprocessor is...   
13           13  nothing good about this phone other than the c...   
14           14  i got this phone within two days the delivery ...   
15           15  this mobile is superb everything things is gre...   
16           16  im happy to this mobile phone bettry is good v...   
17           17  well its good for simple work and capture good...   
18           18  camera is goodthe battery backup is strongat t...   
19           19  have received the product today and the phone ...   
20           20  very fast delivery by flipkart excellent phone...   
21           21  excellent smartphone presented by xiaomi brand...   
22           22  very nice mobile its display is very nice and ...   
23           23  attractive colour n specs value for money prod...   
24           24  very nice mobile phonecolour is best and displ...   
25           25  very impressive mobilelook like is very awesom...   
26           26  very good phone in lowest budget and good perf...   
27           27  this is my second low budget mi phone first on...   
28           28  super phone i gifted my dad he was very happy ...   
29           29  very nice amazing phone valu for money good ba...   
..          ...                                                ...   
470         470  its very good phone for people who needs good ...   
471         471  in india one of the best app flip cart redmimo...   
472         472  mobile is good but the camera is onlymp so com...   
473         473  its awesome product in low cost thank you once...   
474         474  simply best choice underone cant get a best sp...   
475         475  very good phone at range its awesome the look ...   
476         476  very nice mobile and battery back up is very g...   
477         477  phone is quite good specially in the battery p...   
478         478  its awesome product in low cost thank you once...   
479         479  phone is stylish and good but battery back up ...   
480         480  just wanna say at this price range at present ...   
481         481  nice and so good worth for money we spendvery ...   
482         482  received an very fresh piece it rocks shines i...   
483         483  super mobal price for satisfied good response ...   
484         484  value for money nice product get battery pick ...   
485         485  xiaomi is just awesomethe ease of use that the...   
486         486  if you are looking for a feel good phone with ...   
487         487  good quality with nice features at affordable ...   
488         488  good product stylish design and super display ...   
489         489  awesome purchase incamera awesome battery life...   
490         490  better option available in this price like rea...   
491         491  great mobile awesome battery backup really goo...   
492         492  very good smart budget phone at this price fea...   
493         493  alwya want to shop only on flipkartbecause of ...   
494         494  nice product with affordable price thanks xiao...   
495         495

In [6]:
table_rev = fk_rev.copy()
#print(table)
table_rev.head()

Unnamed: 0                                             Review  \
0           0  i am spellbound after seeing thiswhat a value ...   
1           1  overall the screen of the redmiis pretty good ...   
2           2  awesome mobile ive purchased it for my mom she...   
3           3  very good phonenice display andlong battery li...   
4           4  super budget mobile i like type c portbig exce...   

                                              tokens  \
0  ['i', 'am', 'spellbound', 'after', 'seeing', '...   
1  ['overall', 'the', 'screen', 'of', 'the', 'red...   
2  ['awesome', 'mobile', 'ive', 'purchased', 'it'...   
3  ['very', 'good', 'phonenice', 'display', 'andl...   
4  ['super', 'budget', 'mobile', 'i', 'like', 'ty...   

                                          tokens_seg  \
0  ['i', 'am', 'spellbound', 'after', 'seeing', '...   
1  ['overall', 'the', 'screen', 'of', 'the', 'red...   
2  ['awesome', 'mobile', 'ive', 'purchased', 'it'...   
3  ['very', 'good', 'phone', 'nice', 'display', '...   
4  ['super', 'budget', 'mobile', 'i', 'like', 'ty...   

                                         tokens_stem  \
0  ['spellbound', 'see', 'valu', 'money', 'love',...   
1  ['overal', 'screen', 'red', 'mi', 'pretti', 'g...   
2  ['awesom', 'mobil', 'ive', 'purchas', 'mom', '...   
3  ['good', 'phone', 'nice', 'display', 'long', '...   
4  ['super', 'budget', 'mobil', 'like', 'type', '...   

                                             review1  
0  spellbound see valu money love mi also packag ...  
1  overal screen red mi pretti good consid sub rs...  
2  awesom mobil ive purchas mom happi surpris guy...  
3  good phone nice display long batteri life good...  
4  super budget mobil like type c port big excel ...

In [7]:
table = pd.DataFrame(columns = ['Review','Camera','Battery','Price','Display'])
print(table)

Empty DataFrame
Columns: [Review, Camera, Battery, Price, Display]
Index: []


In [8]:
for rev in table_rev['Review']:
    review = rev
    c=0
    b=0
    p=0
    d=0
    o=0
    s=0
    st=0
    m=0
    if 'camera' in rev:
        c=1
    if 'battery' in rev:
        b=1
    if 'price' in rev or 'cost' in rev or 'budget' in rev:
        p=1
    if 'display' in rev or 'screen' in rev or 'graphic' in rev:
        d=1
    '''if 'styl' in rev or 'color' in rev or 'colour' in rev or 'thin'  in rev or 'feature' in rev:
        st=1
    if 'memory' in rev or 'mb' in rev or 'gb' in rev or 'storage' in rev or 'space' in rev:
        m=1
    if 'service' in rev or 'deliver' in rev:
        s=1
    if c==0 and b==0 and p==0 and d==0 and s==0 and st==0 and m==0:
        o=1'''
    #table = table.append({'Review' : rev ,'Camera' : c, 'Battery' : b, 'Price' : p, 'Display' : d, 'Style' : st , 'Memory' : m , 'Service' : s, 'Others' : o}, 
               #ignore_index = True)
    table = table.append({'Review' : rev ,'Camera' : c, 'Battery' : b, 'Price' : p, 'Display' : d},ignore_index=True)
table = table.fillna(0)
#table.iloc[1]['Review']
table.head()

Review  Camera  Battery  Price  \
0  i am spellbound after seeing thiswhat a value ...       0        0      0   
1  overall the screen of the redmiis pretty good ...       0        1      1   
2  awesome mobile ive purchased it for my mom she...       0        0      0   
3  very good phonenice display andlong battery li...       1        1      1   
4  super budget mobile i like type c portbig exce...       0        0      1   

   Display  
0        0  
1        1  
2        0  
3        1  
4        0

In [9]:
import pandas as pd
import numpy as np
!pip install scikit-multilearn
from skmultilearn.adapt import MLkNN
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score

You should consider upgrading via the 'c:\users\ankit\anaconda3\python.exe -m pip install --upgrade pip' command.


In [10]:
aspects_df = table.copy()
aspects_df.head()
aspects_df.iloc[0]
aspects_df.head()

Review  Camera  Battery  Price  \
0  i am spellbound after seeing thiswhat a value ...       0        0      0   
1  overall the screen of the redmiis pretty good ...       0        1      1   
2  awesome mobile ive purchased it for my mom she...       0        0      0   
3  very good phonenice display andlong battery li...       1        1      1   
4  super budget mobile i like type c portbig exce...       0        0      1   

   Display  
0        0  
1        1  
2        0  
3        1  
4        0

In [11]:
X=table_rev["review1"]
y = np.asarray(aspects_df[aspects_df.columns[1:]])
X
#y

0      spellbound see valu money love mi also packag ...
1      overal screen red mi pretti good consid sub rs...
2      awesom mobil ive purchas mom happi surpris guy...
3      good phone nice display long batteri life good...
4      super budget mobil like type c port big excel ...
5      smoothli phone work also light weight thin eas...
6      nice phone good batteri life amaz design camer...
7         red mi good phone good processor good good ram
8      stun look good power perform pie awesom valu m...
9      wow great phone camera super batteri good happ...
10     som product point view red mi must buy mobil p...
11     honest review honest buyer know lot pro one ma...
12     good phone batteri camera good processor good ...
13     noth good phone cost heavi display dull rear c...
14     got phone within two day deliveri servic aweso...
15     mobil superb everyth thing great batteri backu...
16     im happi mobil phone bet tri good valu money b...
17     well good simpl work cap

In [12]:
vetorizar = TfidfVectorizer(max_features=100,max_df=0.85)
vetorizar.fit(X)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=0.85, max_features=100,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)
#print((y_train))
for i in y_train:
    if len(set(i))==1:
        print("YES")

YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES
YES


In [14]:
X_train_tfidf = vetorizar.transform(X_train)
X_test_tfidf = vetorizar.transform(X_test)

In [15]:
X_train_tfidf.shape,y_train.shape

((400, 100), (400, 4))

In [16]:
mlknn_classifier = MLkNN()
mlknn_classifier.fit(X_train_tfidf, y_train)
score = mlknn_classifier.score(X_test_tfidf, y_test)
print(y_train)
print((y_test))
print(score)

[[0 1 0 0]
 [1 1 0 0]
 [0 1 0 1]
 ...
 [1 1 0 0]
 [1 0 0 0]
 [0 0 0 0]]
[[1 1 1 0]
 [0 1 0 0]
 [1 1 1 1]
 [1 1 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 0 0]
 [1 0 0 1]
 [0 0 0 0]
 [1 1 0 1]
 [0 0 0 0]
 [1 1 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 1]
 [1 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [1 1 1 1]
 [0 1 0 0]
 [1 0 0 1]
 [0 1 1 0]
 [1 0 0 1]
 [1 0 0 0]
 [1 1 1 1]
 [1 0 0 1]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 0 0]
 [1 1 0 1]
 [1 1 0 1]
 [0 0 1 0]
 [1 0 0 1]
 [0 1 1 0]
 [1 1 1 0]
 [0 0 0 0]
 [0 0 1 0]
 [1 1 0 0]
 [0 1 0 1]
 [0 0 1 0]
 [1 1 0 1]
 [0 1 1 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 1 1 1]
 [0 1 1 0]
 [1 1 1 1]
 [1 0 0 0]
 [0 1 1 0]
 [1 1 0 1]
 [0 0 0 0]
 [0 0 1 0]
 [0 1 0 1]
 [0 0 0 0]
 [1 1 0 1]
 [0 1 0 0]
 [1 1 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [0 0 0 0]
 [1 0 1 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 1 0]
 [1 1 1 0]
 [0 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 0]
 [1 1 1 1]
 [1 1 0 0]
 [0 1 0 0]
 [1 1 1 0]
 [1 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 0]
 [1 0 1 0]
 [0 0 1 0]
 [0 0 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 

In [17]:
# using classifier chains
from skmultilearn.problem_transform import ClassifierChain
from sklearn.linear_model import LogisticRegression
# initialize classifier chains multi-label classifier
classifier = ClassifierChain(LogisticRegression())
# Training logistic regression model on train data
classifier.fit(X_train_tfidf, y_train)
# predict
predictions = classifier.predict(X_test_tfidf)
# accuracy
print("Accuracy = ",accuracy_score(y_test,predictions))
print("\n")

Accuracy =  0.69




C:\Users\ankit\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ankit\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ankit\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ankit\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [18]:
from skmultilearn.adapt import MLkNN
from scipy.sparse import csr_matrix, lil_matrix
classifier_new = MLkNN(k=10)
# Note that this classifier can throw up errors when handling sparse matrices.
x_train = lil_matrix(X_train_tfidf).toarray()
y_train = lil_matrix(y_train).toarray()
x_test = lil_matrix(X_test_tfidf).toarray()
# train
classifier_new.fit(x_train, y_train)
# predict
predictions_new = classifier_new.predict(x_test)
# accuracy
print("Accuracy = ",accuracy_score(y_test,predictions_new))
print("\n")


Accuracy =  0.39




In [ ]:
s=input()
s.lower()
from wordsegment import load,segment
load()
def word_seg(text):
    stem_text =[]
    for i in text:
        stem_text=stem_text+segment(i)
    return stem_text
s=word_seg(s)
print(s)
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
all_stopwords.remove("isn't")
def portstem(text):
    review = [ps.stem(word) for word in text if not word in set(all_stopwords)]
    return review
temp=portstem(s)
print(temp)
new_sentences = [s] 
new_sentence_tfidf = vetorizar.transform(new_sentences)
predicted_sentences = mlknn_classifier.predict(new_sentence_tfidf) 
print(predicted_sentences.toarray()) 